CREATE TABLE [dbo].[Clients]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[EventCallbackUrl] NVARCHAR(500) DEFAULT '' NOT NULL,
	[CreatedDate] DATETIME2 DEFAULT GETDATE() NOT NULL 
)
